info:
  component: Config Server
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://git.oschina.net/xixingzhe2/config.git

server:
  port: 8888
